from server.tasks.base import ControlProfile, DisturbanceProfile, MissionTask, TaskConfig, TimedTarget


class MediumTask(MissionTask):
    def __init__(self) -> None:
        super().__init__(
            TaskConfig(
                task_id="retarget_180_flip",
                difficulty="medium",
                title="Retarget High-Gain Antenna",
                description="Execute a near-180 degree slew, brake cleanly, and settle without overshoot.",
                mission_brief="Maintain the old target through a quiet window, then pivot the bus to a new ground-station geometry without wasting fuel or overshooting.",
                mission_summary="The spacecraft must repoint a high-gain antenna to a new ground station geometry.",
                initial_attitude_deg=(0.0, -1.0, 2.0),
                initial_rates_dps=(0.02, -0.03, 0.01),
                target_schedule=(
                    TimedTarget(
                        start_step=0,
                        phase="tracking_old_target",
                        attitude_deg=(0.0, 0.0, 0.0),
                        instruction="Hold the incumbent target until the retarget window opens. Do not churn fuel before the maneuver begins.",
                        deadline_step=18,
                        milestone="pre_slew_stable",
                        recommended_modes=("hold", "trim", "safe_hold"),
                        fuel_reserve_target=95.0,
                        completion_tolerance_deg=1.5,
                        completion_rate_tolerance_dps=0.12,
                        completion_hold_steps=6,
                    ),
                    TimedTarget(
                        start_step=18,
                        phase="slew_window",
                        attitude_deg=(178.0, 14.0, -9.0),
                        instruction="Slew aggressively at first, brake before the 180-degree flip overshoots, then settle on the new antenna target.",
                        deadline_step=120,
                        milestone="new_target_locked",
                        recommended_modes=("slew", "brake", "trim", "hold"),
                        fuel_reserve_target=28.0,
                        completion_tolerance_deg=1.5,
                        completion_rate_tolerance_dps=0.12,
                        completion_hold_steps=16,
                    ),
                ),
                anomaly_schedule=(),
                step_budget=180,
                time_step_seconds=1.8,
                inertia=(2.6, 2.4, 2.9),
                damping=(0.16, 0.15, 0.13),
                control_profile=ControlProfile(
                    small_impulse_dps=0.48,
                    large_impulse_dps=0.95,
                    small_fuel_cost=0.75,
                    large_fuel_cost=1.45,
                ),
                disturbance_profile=DisturbanceProfile(
                    seed=29,
                    bias_dps2=(0.0025, -0.0015, 0.0012),
                    min_amplitude_dps2=0.0010,
                    max_amplitude_dps2=0.0030,
                    frequency_scale=0.85,
                    reported_level=0.16,
                ),
                fuel_capacity=120.0,
                fuel_reserve_success=18.0,
                final_tolerance_deg=1.5,
                angular_rate_tolerance_dps=0.12,
                hold_streak_success=16,
                fuel_budget=78.0,
                mean_error_success=5.0,
                on_target_fraction_success=0.20,
                overshoot_budget=3.5,
                early_success_allowed=True,
                required_milestones=0,
                pointing_scale_deg=22.0,
                fuel_penalty_coeff=0.035,
                stability_penalty_coeff=0.05,
                overshoot_penalty_coeff=0.08,
                hold_bonus_coeff=0.010,
            )
        )
