from server.tasks.base import (
    ControlProfile,
    DisturbanceProfile,
    MissionAnomaly,
    MissionTask,
    TaskConfig,
    TimedTarget,
)


class FlagshipMissionTask(MissionTask):
    def __init__(self) -> None:
        super().__init__(
            TaskConfig(
                task_id="mission_ops_long_horizon",
                difficulty="hard",
                title="Mission Ops Relay Recovery Chain",
                description="Chain detumble, coast discipline, retargeting, anomaly recovery, and precision hold into one delayed-reward mission episode.",
                mission_brief="A relay spacecraft must survive deployment, honor a quiet coast window, repoint to a new relay geometry, recover from a gyro bias spike, and finish in precision hold with fuel in reserve. The task is explicitly long-horizon: early waste breaks later phases.",
                mission_summary="This flagship Theme #2 benchmark stresses instruction tracking, deferred rewards, and recovery from early mistakes across a multi-phase spacecraft mission.",
                initial_attitude_deg=(9.5, -6.2, 13.0),
                initial_rates_dps=(0.52, -0.37, 0.43),
                target_schedule=(
                    TimedTarget(
                        start_step=0,
                        phase="detumble_window",
                        attitude_deg=(0.0, 0.0, 0.0),
                        instruction="Deployment complete. Detumble the bus and settle on the neutral handover attitude before the coast window opens.",
                        deadline_step=42,
                        milestone="deployment_detumbled",
                        recommended_modes=("detumble", "trim", "hold"),
                        fuel_reserve_target=76.0,
                        completion_tolerance_deg=2.0,
                        completion_rate_tolerance_dps=0.16,
                        completion_hold_steps=8,
                    ),
                    TimedTarget(
                        start_step=42,
                        phase="coast_window",
                        attitude_deg=(0.0, 0.0, 0.0),
                        instruction="Quiet coast period. Maintain attitude with minimal actuation and preserve fuel for the retarget burn.",
                        deadline_step=84,
                        milestone="coast_window_cleared",
                        recommended_modes=("hold", "trim", "safe_hold"),
                        fuel_reserve_target=68.0,
                        completion_tolerance_deg=1.8,
                        completion_rate_tolerance_dps=0.12,
                        completion_hold_steps=10,
                    ),
                    TimedTarget(
                        start_step=84,
                        phase="retarget_window",
                        attitude_deg=(132.0, -24.0, 47.0),
                        instruction="Retarget to the relay geometry. Start with a committed slew, brake before overshoot, then settle for anomaly monitoring.",
                        deadline_step=156,
                        milestone="relay_retargeted",
                        recommended_modes=("slew", "brake", "trim", "hold"),
                        fuel_reserve_target=38.0,
                        completion_tolerance_deg=1.8,
                        completion_rate_tolerance_dps=0.12,
                        completion_hold_steps=12,
                    ),
                    TimedTarget(
                        start_step=156,
                        phase="anomaly_recovery",
                        attitude_deg=(132.0, -24.0, 47.0),
                        instruction="Gyro bias spike detected. Arrest rate growth, re-establish safe pointing, and do not burn through the reserve while recovering.",
                        deadline_step=228,
                        milestone="gyro_bias_stabilized",
                        recommended_modes=("recover", "safe_hold", "trim"),
                        fuel_reserve_target=24.0,
                        completion_tolerance_deg=2.2,
                        completion_rate_tolerance_dps=0.10,
                        completion_hold_steps=10,
                    ),
                    TimedTarget(
                        start_step=228,
                        phase="precision_hold",
                        attitude_deg=(132.0, -24.0, 47.0),
                        instruction="Return to mission precision hold and stay inside the fine-pointing envelope through mission end.",
                        deadline_step=360,
                        milestone="relay_locked",
                        recommended_modes=("hold", "trim", "safe_hold"),
                        fuel_reserve_target=12.0,
                        completion_tolerance_deg=1.0,
                        completion_rate_tolerance_dps=0.08,
                        completion_hold_steps=24,
                    ),
                ),
                anomaly_schedule=(
                    MissionAnomaly(
                        start_step=156,
                        end_step=220,
                        flag="gyro_bias_spike",
                        note="Attitude gyro bias spike injects persistent apparent rate drift and amplifies disturbances.",
                        disturbance_scale=1.8,
                        rate_bias_dps=(0.08, -0.05, 0.06),
                        recommended_modes=("recover", "safe_hold"),
                    ),
                ),
                step_budget=360,
                time_step_seconds=8.0,
                inertia=(3.1, 2.7, 3.5),
                damping=(0.12, 0.11, 0.10),
                control_profile=ControlProfile(
                    small_impulse_dps=0.34,
                    large_impulse_dps=0.82,
                    small_fuel_cost=0.46,
                    large_fuel_cost=1.08,
                ),
                disturbance_profile=DisturbanceProfile(
                    seed=113,
                    bias_dps2=(0.0018, -0.0013, 0.0015),
                    min_amplitude_dps2=0.0008,
                    max_amplitude_dps2=0.0032,
                    frequency_scale=0.95,
                    reported_level=0.21,
                ),
                fuel_capacity=90.0,
                fuel_reserve_success=10.0,
                final_tolerance_deg=1.0,
                angular_rate_tolerance_dps=0.08,
                hold_streak_success=24,
                fuel_budget=48.0,
                mean_error_success=2.2,
                on_target_fraction_success=0.42,
                overshoot_budget=5.0,
                early_success_allowed=False,
                required_milestones=5,
                pointing_scale_deg=16.0,
                fuel_penalty_coeff=0.05,
                stability_penalty_coeff=0.06,
                overshoot_penalty_coeff=0.08,
                hold_bonus_coeff=0.010,
            )
        )
